// <auto-generated />
namespace justinobney.gymbuddy.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Appointment_AddGym : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointment_AddGym));
        
        string IMigrationMetadata.Id
        {
            get { return "201603141246018_Appointment_AddGym"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
