// <auto-generated />
namespace justinobney.gymbuddy.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Device_AddPushToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Device_AddPushToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201602250336070_Device_AddPushToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
