// <auto-generated />
namespace justinobney.gymbuddy.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gym_InitialAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gym_InitialAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201602040427028_Gym_InitialAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
